# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            justaddScott
tagline:          'add a pinch of Scott'
description:      ''
url:              http://justaddscott.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Scott Frye'
  url:            https://twitter.com/justaddscott

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
